name: Test (make)
on:
  workflow_call:
    inputs:
      plugin:
        required: true
        type: string
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        otp_version:
        - 26.2
        metadata_store:
          - mnesia
          - khepri
    timeout-minutes: 120
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v4
    - name: SETUP ERLANG/ELIXIR
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: 1.15
    - name: BUILD
      run: |
        make \
          RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
    - name: TEST rabbit
      run: |
        make -C deps/${{ inputs.plugin }} \
          tests \
          RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
    - name: UPLOAD TEST ARTIFACTS
      if: always()
      uses: actions/upload-artifact@v4.3.1
      with:
        name: testlogs-${{ inputs.plugin }}-${{ matrix.metadata_store }}-${{ matrix.otp_version }}
        path: |
          logs/*
