name: Test (make)
on:
  workflow_call:
    inputs:
      trc:
        required: true
        type: string
      plugin:
        required: true
        type: string
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        otp_version:
        - 26.2
        metadata_store:
          - mnesia
          - khepri
    timeout-minutes: 120
    env:
      SUCCESS_PATH: ${{ inputs.trc }}/${{ github.sha }}/${{ inputs.plugin }}/${{ matrix.metadata_store }}/${{ matrix.otp_version }}
    steps:
      - name: FETCH TEST RESULT CACHE
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.SUCCESS_PATH }}
          merge-multiple: true
      - name: CHECK IF ALREADY PASSED
        id: check
        run: |
          if [[ -f ${{ env.SUCCESS_PATH }} ]]; then
            echo "passed=true" | tee -a $GITHUB_OUTPUT
          else
            echo "passed=false" | tee -a $GITHUB_OUTPUT
          fi
      - name: CHECKOUT REPOSITORY
        if: steps.check.outputs.passed != 'true'
        uses: actions/checkout@v4
      - name: SETUP ERLANG/ELIXIR
        if: steps.check.outputs.passed != 'true'
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: 1.15
      - name: BUILD
        if: steps.check.outputs.passed != 'true'
        run: |
          make \
            RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
      - name: TEST ${{ inputs.plugin }}
        id: test
        if: steps.check.outputs.passed != 'true'
        run: |
          set -x
          make -C deps/${{ inputs.plugin }} \
            tests \
            RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          mkdir -p $(dirname ${{ env.SUCCESS_PATH }})
          echo "passed" > ${{ env.SUCCESS_PATH }}
      - name: UPDATE CACHE
        if: steps.test.outcome == 'success'
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ inputs.plugin }}-${{ matrix.metadata_store }}-${{ matrix.otp_version }}
          path: |
            ${{ env.SUCCESS_PATH }}
      - name: UPLOAD TEST ARTIFACTS
        if: always() && steps.check.outputs.passed != 'true'
        uses: actions/upload-artifact@v4.3.1
        with:
          name: testlogs-${{ inputs.plugin }}-${{ matrix.metadata_store }}-${{ matrix.otp_version }}
          path: |
            deps/${{ inputs.plugin }}/logs/*
