name: Test (make)
on:
  push:
    branches:
      - main
      - v3.13.x
      - v3.12.x
      - v3.11.x
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test-rabbit:
    uses: ./.github/workflows/test-plugin-make.yaml
    with:
      plugin: rabbit
  summary-test-make:
    needs:
    - test-rabbit
    runs-on: ubuntu-latest
    steps:
    - name: SUMMARY
      run: |
        echo "SUCCESS"
